default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('DB_POOL') { 5 } %>
  timeout: 5000
  template: template0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
